vim.g.go_snippet_engine="UltiSnips"
vim.g.go_fmt_command = "goimports"
vim.g.go_highlight_types = 1
vim.g.go_highlight_fields = 1
vim.g.go_highlight_functions = 1
vim.g.go_highlight_function_calls = 1
vim.g.go_highlight_operators = 1
vim.g.go_highlight_extra_types = 1
vim.g.go_highlight_operators = 1
vim.g.go_highlight_function_parameters = 1
vim.g.go_highlight_format_strings = 1
vim.g.go_def_mode = "gopls"
vim.g.go_info_mode = "gopls"
